/*
 *  Copyright (c) 2014, Lukas Tenbrink.
 *  * http://lukas.axxim.net
 */

// Date: 25.10.2014 18:50:32
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package ivorius.psychedelicraft.client.rendering;

import ivorius.ivtoolkit.items.IvItemRendererModel;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.item.ItemStack;

public class ModelDistillery extends ModelBase implements IvItemRendererModel.ItemModelRenderer
{
    //fields
    ModelRenderer base;
    ModelRenderer baseTop;
    ModelRenderer baseSide0;
    ModelRenderer baseSide1;
    ModelRenderer topSide1;
    ModelRenderer topSide2;
    ModelRenderer condenser;

    public ModelDistillery()
    {
        textureWidth = 64;
        textureHeight = 32;

        base = new ModelRenderer(this, 0, 20);
        base.addBox(-3F, -4F, -3F, 6, 6, 6);
        base.setRotationPoint(0F, 22F, 0F);
        base.setTextureSize(64, 32);
        base.mirror = true;
        setRotation(base, 0F, 0F, 0F);
        baseTop = new ModelRenderer(this, 48, 20);
        baseTop.addBox(-2F, -2F, -2F, 4, 8, 4);
        baseTop.setRotationPoint(0F, 12F, 0F);
        baseTop.setTextureSize(64, 32);
        baseTop.mirror = true;
        setRotation(baseTop, 0F, 0F, 0F);
        baseSide0 = new ModelRenderer(this, 40, 0);
        baseSide0.addBox(-2F, -2F, -4F, 4, 5, 8);
        baseSide0.setRotationPoint(0F, 21F, 0F);
        baseSide0.setTextureSize(64, 32);
        baseSide0.mirror = true;
        setRotation(baseSide0, 0F, 0F, 0F);
        baseSide1 = new ModelRenderer(this, 24, 23);
        baseSide1.addBox(-4F, -2F, -2F, 8, 5, 4);
        baseSide1.setRotationPoint(0F, 21F, 0F);
        baseSide1.setTextureSize(64, 32);
        baseSide1.mirror = true;
        setRotation(baseSide1, 0F, 0F, 0F);
        topSide1 = new ModelRenderer(this, 16, 0);
        topSide1.addBox(-1F, -2F, -3F, 4, 4, 6);
        topSide1.setRotationPoint(-1F, 13F, 0F);
        topSide1.setTextureSize(64, 32);
        topSide1.mirror = true;
        setRotation(topSide1, 0F, 0F, 0F);
        topSide2 = new ModelRenderer(this, 28, 15);
        topSide2.addBox(-2F, -2F, -2F, 6, 4, 4);
        topSide2.setRotationPoint(-1F, 13F, 0F);
        topSide2.setTextureSize(64, 32);
        topSide2.mirror = true;
        setRotation(topSide2, 0F, 0F, 0F);
        condenser = new ModelRenderer(this, 0, 6);
        condenser.addBox(0F, -3F, 2.3F, 1, 1, 13);
        condenser.setRotationPoint(-0.5F, 13.3F, -0.3F);
        condenser.setTextureSize(64, 32);
        condenser.mirror = true;
        setRotation(condenser, -0.2974289F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        base.render(f5);
        baseTop.render(f5);
        baseSide0.render(f5);
        baseSide1.render(f5);
        topSide1.render(f5);
        topSide2.render(f5);
        condenser.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    @Override
    public void render(ItemStack stack)
    {
        float f5 = 0.0625F;
        base.render(f5);
        baseTop.render(f5);
        baseSide0.render(f5);
        baseSide1.render(f5);
        topSide1.render(f5);
        topSide2.render(f5);
        condenser.render(f5);
    }
}
